name: fanme_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  flutter_local_notifications: ^1.2.1
  auto_route: ^0.3.1
  flushbar: ^1.9.1
  ff_navigation_bar: ^0.1.4
  font_awesome_flutter: ^8.7.0
  flutter_svg: ^0.17.1
  uuid: ^2.0.4
  localstorage: ^3.0.0
  validators: ^2.0.0
  flutter_spinkit: ^4.1.2
  cupertino_icons: ^0.1.3
  equatable: ^1.1.0
  flutter_bloc: ^3.2.0
  simple_animations: ^1.3.8
  email_validator: "^1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^0.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-lightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
